events {
    worker_connections 1024;   # Max conexiones simultaneas por worker
}

http {
    upstream auth-backend {
        server auth-service:8081;
    }

    upstream user-backend {
        server user-service:8080;
    }

    upstream frontend {
        server frontend:4200;  # Angular dev server port
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $realip_remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;

            proxy_pass http://auth-backend;
        }

        location /api/users/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $realip_remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;

            proxy_pass http://user-backend;
        }

        location /graphql {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $realip_remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;

            proxy_pass http://user-backend;
        }

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $realip_remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization;


            proxy_pass http://frontend;
        }
    }
}
